### ISSUE TITLE
check (-c) feature broken

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_master#50]
the `-c` option does not have an effect, i.e. `esm_master get-foci-default -c` does exactly the same as `esm_master get-foci-default`. Can anyone confirm this?

**Comment by seb-wahl** [comment]
It used to work perfectly prior to (I think) version 5.1

**Comment by denizural** [comment]
Yes, I just checked and got the same thing. I am having a look

**Comment by denizural** [comment]
Hi @seb-wahl, I made a PR. Could you also test and verify that they work. Then, I can merge and bump and close the issue.

**Comment by denizural** [comment]
Merged the hotfix into both release and develop & updated the patch version. Closing the issue.
